<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="MyDefault Test Suite" duration-ms="32" started-at="2016-11-16T16:27:23Z" finished-at="2016-11-16T16:27:23Z">
    <groups>
    </groups>
    <test name="Command line test 8ca6219f-6983-4827-80e0-1af03ba988a9" duration-ms="32" started-at="2016-11-16T16:27:23Z" finished-at="2016-11-16T16:27:23Z">
      <class name="com.test.calculator.CalcTest">
        <test-method status="PASS" signature="add(int, int, int)[pri:0, instance:com.test.calculator.CalcTest@2af02b8a]" name="add" duration-ms="5" started-at="2016-11-16T21:57:23Z" data-provider="defaultDP" finished-at="2016-11-16T21:57:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[20]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[30]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add -->
        <test-method status="PASS" signature="add(int, int, int)[pri:0, instance:com.test.calculator.CalcTest@2af02b8a]" name="add" duration-ms="0" started-at="2016-11-16T21:57:23Z" data-provider="defaultDP" finished-at="2016-11-16T21:57:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[34]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[45]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[79]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add -->
        <test-method status="FAIL" signature="add(int, int, int)[pri:0, instance:com.test.calculator.CalcTest@2af02b8a]" name="add" duration-ms="1" started-at="2016-11-16T21:57:23Z" data-provider="defaultDP" finished-at="2016-11-16T21:57:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[11]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[22]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[44]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Addition is Wrong expected [44] but found [33]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Addition is Wrong expected [44] but found [33]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at com.test.calculator.CalcTest.add(CalcTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.mentorstudies.automationframework.TestRunner.main(TestRunner.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add -->
      </class> <!-- com.test.calculator.CalcTest -->
    </test> <!-- Command line test 8ca6219f-6983-4827-80e0-1af03ba988a9 -->
  </suite> <!-- MyDefault Test Suite -->
</testng-results>
